name: Java CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'

            - name: Build with Maven
              run: mvn clean install

            - name: Run Tests
              run: mvn test

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: app

            - name: Prepare SSH known_hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

            - name: Deploy to Server On SSH
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
                  chmod 600 /tmp/ssh_key
                  scp -o StrictHostKeyChecking=no -i /tmp/ssh_key target/Calculator-1.0-SNAPSHOT.jar $SERVER_USER@$SERVER_IP:~/app/
                  ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key $SERVER_USER@$SERVER_IP << 'EOF'
                    nohup java -jar ~/app/Calculator-1.0-SNAPSHOT.jar > ~/app/app.log 2>&1 &
                  EOF
