name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Отладка окружения
          echo "User: $(whoami)"
          echo "Home directory: $HOME"
          ls -ld $HOME || echo "Home directory not found"

          # Создание .ssh (для разных систем)
          mkdir -p $HOME/.ssh || sudo mkdir -p /home/runner/.ssh || sudo mkdir -p /Users/runner/.ssh

          # Запись приватного SSH-ключа
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

          # Добавление сервера в known_hosts
          ssh-keyscan 192.168.111.128 >> $HOME/.ssh/known_hosts
          
          # Деплой на сервер
          ssh user@192.168.111.128 'bash ~/deploy.sh'
